### ISSUE TITLE
Create VM for hosting first cluster

### ISSUE THREAD

**Issue by mischavandenburg** [mischavandenburg/kubecraft#17]
We'll start with running a single node cluster on one VM, just to see how things go.

Write terraform code to create a resource group and one VM with the following tier:

![Image](https://github.com/user-attachments/assets/b36fc0d8-793e-45c6-8407-56e421807dd7)

OS: Ubuntu Server

**Comment by joesabbagh1** [comment]
I would like to work on this!

**Comment by mischavandenburg** [comment]
Great! Note that I have updated it to Terraform.

Perhaps you can team up with someone?

**Comment by clumpspirit** [comment]
@joesabbagh1 Would you like to team up?

**Comment by mischavandenburg** [comment]
Closed #29
