### ISSUE TITLE
Write Terraform code for one Azure Key Vault

### ISSUE THREAD

**Issue by mischavandenburg** [mischavandenburg/kubecraft#27]
Write Terraform code for one Azure Key Vault, to be used with the External Secrets Operator #22

**Comment by clumpspirit** [comment]
I can work on this!

**Comment by mischavandenburg** [comment]
Go for it @clumpspirit !

**Comment by clumpspirit** [comment]
My apologies if my PR semantics and descriptions are not conventional or appropriate; I am quite new to it. Please let me know if there's anything I can approve on.

**Comment by mischavandenburg** [comment]
You are doing great!
